variables:
  DIST_WS: s3://$BUCKETNAME/$CI_PROJECT_NAME/$CI_COMMIT_BRANCH/
stages:
  - build_dist
  - deploy

build_dist:
  stage: build_dist
  only:
    - develop
    - master
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules/
  image: node:20-alpine
  script:
    - npm install
    - |
      if [[ $CI_COMMIT_BRANCH == "develop" ]]; then
        npm run generate:test;
      elif [[ $CI_COMMIT_BRANCH == "master" ]]; then
        npm run generate;
      else
        exit 1;
      fi
  artifacts:
    paths:
      - .output/public/

deploy:
  stage: deploy
  only:
    - develop
    - master
  image: cr.ddit.ai/custom/aws-cli:ci-latest
  script:
    # 输出同步更改
    - aws s3 sync $CI_PROJECT_DIR/.output/public/ $DIST_WS --region $REGION --dryrun
    # 执行同步更改
    - aws s3 sync $CI_PROJECT_DIR/.output/public/ $DIST_WS --region $REGION
    # 执行部署
    - aws amplify start-deployment --app-id $APPID --branch-name $CI_COMMIT_BRANCH --source-url $DIST_WS --source-url-type BUCKET_PREFIX --region $REGION
    - JOB_ID=$(aws amplify list-jobs --app-id $APPID --branch-name $CI_COMMIT_BRANCH --query 'jobSummaries[0].jobId' --no-paginate --output text --region $REGION)
    # 验证部署
    - |
      while true; do
        sleep 5;
        STATUS=$(aws amplify get-job --app-id $APPID --branch-name $CI_COMMIT_BRANCH --job-id $JOB_ID --query 'job.summary.status' --output text --region $REGION);
        if [[ "$STATUS" == "SUCCEED" ]]; then
          aws amplify get-job --app-id $APPID --branch-name $CI_COMMIT_BRANCH --job-id $JOB_ID --query 'job.summary' --region $REGION;
          break;
        fi
      done