events {
    worker_connections 1024;
}
http {
    # 包含 mime 类型，防止 css/js 加载异常
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server {
        # Cloud Run 默认把流量打到 8080
        listen 8080;


        # 1. 定义：遇到 401 错误时，去 @json_401 这个地方处理
        error_page 401 @json_401;

        # 2. 专门负责吐出 JSON 的地方 (Named Location)
        location @json_401 {
            # 强制设置 Content-Type，确保浏览器和 Cloud Run 能看懂
            default_type application/json;
            return 401 '{"error": "Unauthorized", "message": "Missing or Invalid X-Api-Key"}';
        }



        location /health {
            proxy_pass http://127.0.0.1:8000;
        }

        location / {
            if ($http_x_api_key != "${API_KEY}") {
                return 401;
            }

            # 2. 转发给本地的应用容器
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # 禁用 Proxy 缓冲
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_cache_bypass $http_upgrade;     # 避免缓存
            # 禁用缓冲以支持实时数据流
            proxy_buffering off;

            # 增加超时时间以支持长连接
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}