module.exports = {
  ko: 'Korean',
  ja: 'Japanese',
  de: 'German',
  en: 'English (US)',
  'en-us': 'English (US)',
  'es-419': 'Spanish (Latin America)',
  'fr-fr': 'French (France)',
  'pt-br': 'Portuguese (Brazil)',
  fr: 'French (France)',
  ar: 'Arabic',
  bg: 'Bulgarian',
  cs: 'Czech',
  es: 'Spanish (Spain)',
  'es-es': 'Spanish (Spain)',
  'fr-ca': 'French (Canada)',
  el: 'Greek',
  he: 'Hebrew',
  hr: 'Croatian',
  id: 'Indonesian',
  it: 'Italian',
  hu: 'Hungarian',
  nl: 'Dutch',
  nb: 'Norwegian  (Bokmål)',
  pl: 'Polish',
  pt: 'Portuguese (Brazil)',
  'pt-pt': 'Portuguese (Portugal)',
  ro: 'Romanian',
  ru: 'Russian',
  sv: 'Swedish',
  fi: 'Finnish',
  vi: 'Vietnamese',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  'zh-cn': 'Simplified Chinese',
  'zh-hans': 'Simplified Chinese',
  'zh-tw': 'Traditional Chinese (Taiwan)',
  'zh-hk': 'Traditional Chinese (Hong Kong)',
  th: 'Thai',
};
