enum SidepanelEventType {
  SOLVE_FROM_CONTENT = 'SIDEPANEL:SOLVE_FROM_CONTENT', // 内容脚本发送解题请求到后台
  SOLVE_TO_SIDEPANEL = 'SIDEPANEL:SOLVE_TO_SIDEPANEL', // 后台转发解题请求到 sidepanel
  CLOSED = 'SIDEPANEL:CLOSED', // sidepanel 关闭
  READY = 'SIDEPANEL:READY', // sidepanel 准备就绪（打开后）
  OPEN = 'SIDEPANEL:OPEN', // 打开 sidepanel
  TOGGLE = 'SIDEPANEL:TOGGLE', // 切换 sidepanel 显示状态
  SHOW_SCREENSHOT = 'SIDEPANEL:SHOW_SCREENSHOT', // 显示截图界面
  GENERATE_QUIZ_FROM_BUTTON = 'SIDEPANEL:GENERATE_QUIZ_FROM_BUTTON',
  GENERATE_QUIZ_TO_CONTENT = 'SIDEPANEL:GENERATE_QUIZ_TO_CONTENT',
  GENERATE_QUIZ_FROM_CONTENT = 'SIDEPANEL:GENERATE_QUIZ_FROM_CONTENT', // 内容脚本发送侧边栏生成 Quiz 请求
  GENERATE_FROM_CHAT_WITH_PDF = 'SIDEPANEL:GENERATE_FROM_CHAT_WITH_PDF', // feature: 内容脚本发送侧边栏生成 Chat with PDF 请求
  GENERATE_TO_SIDEPANEL_CHAT_WITH_PDF = 'SIDEPANEL:GENERATE_TO_SIDEPANEL_CHAT_WITH_PDF', // feature: 后台转发 Chat with PDF 请求到 sidepanel
  // 新增：内容脚本截图生成（chat/summarize/quiz）
  GENERATE_FROM_SCREENSHOT = 'SIDEPANEL:GENERATE_FROM_SCREENSHOT',
  GENERATE_IMAGE_TO_SIDEPANEL = 'SIDEPANEL:GENERATE_IMAGE_TO_SIDEPANEL',
  GENERATE_QUIZ_FROM_SELECTION = 'SIDEPANEL:GENERATE_QUIZ_FROM_SELECTION', // 内容脚本发送侧边栏生成 Quiz 请求
  GENERATE_QUIZ_TO_SIDEPANEL = 'SIDEPANEL:GENERATE_QUIZ_TO_SIDEPANEL', // 后台转发 Quiz 请求到 sidepanel
  GENERATE_QUIZ_TO_SIDEPANEL_SELECTION = 'SIDEPANEL:GENERATE_QUIZ_TO_SIDEPANEL_SELECTION', // 后台转发 Selection Quiz 请求到 sidepanel
  GENERATE_SUMMARY_FROM_SELECTION = 'SIDEPANEL:GENERATE_SUMMARY_FROM_SELECTION', // 内容脚本发送侧边栏生成 Summary 请求
  GENERATE_SUMMARY_TO_SIDEPANEL_SELECTION = 'SIDEPANEL:GENERATE_SUMMARY_TO_SIDEPANEL_SELECTION', // 后台转发 Summary 请求到 sidepanel
  GENERATE_QUIZ_SUCCESS = 'SIDEPANEL:GENERATE_QUIZ_SUCCESS', // 生成 Quiz 成功
  GENERATE_QUIZ_FAIL = 'SIDEPANEL:GENERATE_QUIZ_FAIL', // 生成 Quiz 失败
  
  GENERATE_QUIZ_FROM_QUIZLET = 'SIDEPANEL:GENERATE_QUIZ_FROM_QUIZLET', // 内容脚本发送 Quizlet Quiz 请求
  GENERATE_QUIZ_TO_SIDEPANEL_QUIZLET = 'SIDEPANEL:GENERATE_QUIZ_TO_SIDEPANEL_QUIZLET', // 后台转发 Quizlet Quiz 请求到 sidepanel

  GENERATE_SUMMARIZE_FROM_SELECTION = 'SIDEPANEL:GENERATE_SUMMARIZE_FROM_SELECTION', // 内容脚本发送 SUMMARIZE 划词请求
  GENERATE_SUMMARIZE_TO_SIDEPANEL_SELECTION = 'SIDEPANEL:GENERATE_SUMMARIZE_TO_SIDEPANEL_SELECTION', // 后台转发 SUMMARIZE 划词请求到 sidepanel

  GENERATE_EXPLAIN_FROM_SELECTION = 'SIDEPANEL:GENERATE_EXPLAIN_FROM_SELECTION', // 内容脚本发送 EXPLAIN 划词请求
  GENERATE_EXPLAIN_TO_SIDEPANEL_SELECTION = 'SIDEPANEL:GENERATE_EXPLAIN_TO_SIDEPANEL_SELECTION', // 后台转发 EXPLAIN 划词请求到 sidepanel

  GENERATE_CHAT_FROM_SELECTION = 'SIDEPANEL:GENERATE_CHAT_FROM_SELECTION', // 内容脚本发送 CHAT 划词请求
  GENERATE_CHAT_TO_SIDEPANEL_SELECTION = 'SIDEPANEL:GENERATE_CHAT_TO_SIDEPANEL_SELECTION', // 后台转发 CHAT 划词请求到 sidepanel

  GET_PAGE_CONTENT = 'SIDEPANEL:GET_PAGE_CONTENT', // 获取页面内容
  GET_PAGE_CONTENT_TYPE = 'SIDEPANEL:GET_PAGE_CONTENT_TYPE', // 获取页面内容类型
  GET_PAGE_HTML_AND_IMAGES = 'SIDEPANEL:GET_PAGE_HTML_AND_IMAGES', // 获取页面HTML和图片列表
  PAGE_HTML_AND_IMAGES_RESPONSE = 'SIDEPANEL:PAGE_HTML_AND_IMAGES_RESPONSE', // 页面HTML和图片列表响应
  SHOW_CLOSE_MODAL = 'SIDEPANEL:SHOW_CLOSE_MODAL', // 显示关闭模态框
  // 登录相关的事件, 需要打开侧边栏等待登录
  LOGIN_REQUEST_FROM_CONTENT = 'SIDEPANEL:LOGIN_REQUEST_FROM_CONTENT', // 内容脚本请求登录
  LOGIN_REQUEST_TO_SIDEPANEL = 'SIDEPANEL:LOGIN_REQUEST_TO_SIDEPANEL', // 后台转发登录请求到 sidepanel
  LOGIN_SUCCESS_TO_CONTENT = 'SIDEPANEL:LOGIN_SUCCESS_TO_CONTENT', // sidepanel 登录成功通知内容脚本
  STATUS_CHANGED = 'SIDEPANEL:STATUS_CHANGED', // sidepanel 状态变化通知
  GENERATE_QUIZ_FROM_YOUTUBE = 'SIDEPANEL:GENERATE_QUIZ_FROM_YOUTUBE', // 内容脚本发送 Youtube Quiz 请求
  GENERATE_QUIZ_TO_SIDEPANEL_YOUTUBE = 'SIDEPANEL:GENERATE_QUIZ_TO_SIDEPANEL_YOUTUBE', // 后台转发 Youtube Quiz 请求到 sidepanel
  CHAT_WITH_PDF_UPLOAD_SUCCESS = 'SIDEPANEL:CHAT_WITH_PDF_UPLOAD_SUCCESS',
  CHAT_WITH_PDF_UPLOAD_FAIL = 'SIDEPANEL:CHAT_WITH_PDF_UPLOAD_FAIL', // Chat with PDF 上传失败（统一处理失败和超时）
  // 页面截图相关事件
  GET_PAGE_SCROLL_INFO = 'SIDEPANEL:GET_PAGE_SCROLL_INFO', // 获取页面滚动信息
  SCROLL_TO_POSITION = 'SIDEPANEL:SCROLL_TO_POSITION', // 滚动到指定位置
  RESTORE_SCROLL_POSITION = 'SIDEPANEL:RESTORE_SCROLL_POSITION', // 恢复滚动位置
  PREPARE_PAGE_FOR_SCREENSHOT = 'SIDEPANEL:PREPARE_PAGE_FOR_SCREENSHOT', // 截图前页面处理（隐藏 fixed、去除 sticky）
  RESTORE_PAGE_AFTER_SCREENSHOT = 'SIDEPANEL:RESTORE_PAGE_AFTER_SCREENSHOT', // 截图结束后恢复页面
  YOUTUBE_OUT_LIMIT_TO_SIDEPANEL = 'SIDEPANEL:YOUTUBE_OUT_LIMIT_TO_SIDEPANEL', // 后台转发Youtube余额不足触发三包的请求
  SHOW_PAYWALL_FROM_LAYER = 'SIDEPANEL:SHOW_PAYWALL_FROM_LAYER', // 浮层环境请求打开侧边栏并显示付费弹窗
  SHOW_PAYWALL_TO_SIDEPANEL = 'SIDEPANEL:SHOW_PAYWALL_TO_SIDEPANEL', // 后台转发付费弹窗请求到侧边栏
  SOLVE_ALL_FROM_CONTENT = 'SIDEPANEL:SOLVE_ALL_FROM_CONTENT', // 内容脚本发送 Solve All 请求
  SOLVE_ALL_TO_SIDEPANEL = 'SIDEPANEL:SOLVE_ALL_TO_SIDEPANEL', // 后台转发 Solve All 请求到 sidepanel

  DISPATCH_ONBOARDING_EVENT = 'SIDEPANEL:DISPATCH_ONBOARDING_EVENT', // 分发 onboarding 事件
  CANCEL_SCREENSHOT = 'SIDEPANEL:CANCEL_SCREENSHOT', // 取消截图
  // YouTube 总结完成事件
  YOUTUBE_SUMMARY_COMPLETED_TO_SIDEPANEL = 'SIDEPANEL:YOUTUBE_SUMMARY_COMPLETED_TO_SIDEPANEL',
  // 浮层推送消息到侧边栏
  LAYER_TO_SIDEPANEL_PUSH_MESSAGES = 'SIDEPANEL:LAYER_TO_SIDEPANEL_PUSH_MESSAGES',
  // 浮层激活 Quote Staging
  ACTIVATE_QUOTE_STAGING = 'SIDEPANEL:ACTIVATE_QUOTE_STAGING',
  // 检查侧边栏是否正在解题（内容脚本请求）
  CHECK_SIDEPANEL_SOLVING = 'SIDEPANEL:CHECK_SIDEPANEL_SOLVING',
  // 侧边栏响应是否正在解题
  CHECK_SIDEPANEL_SOLVING_RESPONSE = 'SIDEPANEL:CHECK_SIDEPANEL_SOLVING_RESPONSE',
  // Canvas 抓取相关事件
  CANVAS_CAPTURE_COMPLETE = 'CANVAS:CAPTURE_COMPLETE', // 内容脚本发送完成信号
}

export default SidepanelEventType
