// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const EffectScope: typeof import('vue')['EffectScope']
  const ImageProcessor: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/imageProcessor')['ImageProcessor']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const browser: typeof import('wxt/browser')['browser']
  const buildHeaders: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/agentUrl')['buildHeaders']
  const computed: typeof import('vue')['computed']
  const convertDOMToMarkdown: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/page')['convertDOMToMarkdown']
  const createApp: typeof import('vue')['createApp']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const customRef: typeof import('vue')['customRef']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const effectScope: typeof import('vue')['effectScope']
  const ensureConnection: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['ensureConnection']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const getActiveTab: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['getActiveTab']
  const getAgentUrl: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/agentUrl')['getAgentUrl']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getCurrentTabUrl: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['getCurrentTabUrl']
  const getLocalAgentUrl: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/agentUrl')['getLocalAgentUrl']
  const getRemoteApiKey: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/agentUrl')['getRemoteApiKey']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const injectScript: typeof import('wxt/client')['injectScript']
  const isInjectableTab: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['isInjectableTab']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const isRemoteMode: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/agentUrl')['isRemoteMode']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const pingContentScript: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['pingContentScript']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const requestInjectContentScript: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['requestInjectContentScript']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const sendMessageToContent: typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['sendMessageToContent']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const storage: typeof import('wxt/storage')['storage']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useAttrs: typeof import('vue')['useAttrs']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useId: typeof import('vue')['useId']
  const useModel: typeof import('vue')['useModel']
  const useSlots: typeof import('vue')['useSlots']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ImageProcessor } from '/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/imageProcessor'
  import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/imageProcessor')
  // @ts-ignore
  export type { ImageInfo, ConvertResult } from '/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/page'
  import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/page')
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly ContentScriptContext: UnwrapRef<typeof import('wxt/client')['ContentScriptContext']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly ImageProcessor: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/imageProcessor')['ImageProcessor']>
    readonly InvalidMatchPattern: UnwrapRef<typeof import('wxt/sandbox')['InvalidMatchPattern']>
    readonly MatchPattern: UnwrapRef<typeof import('wxt/sandbox')['MatchPattern']>
    readonly MigrationError: UnwrapRef<typeof import('wxt/storage')['MigrationError']>
    readonly browser: UnwrapRef<typeof import('wxt/browser')['browser']>
    readonly buildHeaders: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/agentUrl')['buildHeaders']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly convertDOMToMarkdown: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/page')['convertDOMToMarkdown']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createIframeUi: UnwrapRef<typeof import('wxt/client')['createIframeUi']>
    readonly createIntegratedUi: UnwrapRef<typeof import('wxt/client')['createIntegratedUi']>
    readonly createShadowRootUi: UnwrapRef<typeof import('wxt/client')['createShadowRootUi']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAppConfig: UnwrapRef<typeof import('wxt/sandbox')['defineAppConfig']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineBackground: UnwrapRef<typeof import('wxt/sandbox')['defineBackground']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineConfig: UnwrapRef<typeof import('wxt')['defineConfig']>
    readonly defineContentScript: UnwrapRef<typeof import('wxt/sandbox')['defineContentScript']>
    readonly defineUnlistedScript: UnwrapRef<typeof import('wxt/sandbox')['defineUnlistedScript']>
    readonly defineWxtPlugin: UnwrapRef<typeof import('wxt/sandbox')['defineWxtPlugin']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly ensureConnection: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['ensureConnection']>
    readonly fakeBrowser: UnwrapRef<typeof import('wxt/testing')['fakeBrowser']>
    readonly getActiveTab: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['getActiveTab']>
    readonly getAgentUrl: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/agentUrl')['getAgentUrl']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentTabUrl: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['getCurrentTabUrl']>
    readonly getLocalAgentUrl: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/agentUrl')['getLocalAgentUrl']>
    readonly getRemoteApiKey: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/agentUrl')['getRemoteApiKey']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly injectScript: UnwrapRef<typeof import('wxt/client')['injectScript']>
    readonly isInjectableTab: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['isInjectableTab']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isRemoteMode: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/agentUrl')['isRemoteMode']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly pingContentScript: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['pingContentScript']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly requestInjectContentScript: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['requestInjectContentScript']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly sendMessageToContent: UnwrapRef<typeof import('/Users/mac/Documents/code/PluginCode/solvely-mvp/src/utils/connectionHelper')['sendMessageToContent']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storage: UnwrapRef<typeof import('wxt/storage')['storage']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAppConfig: UnwrapRef<typeof import('wxt/client')['useAppConfig']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}
